on:
  push:
    branches:
      - dev
name: 🚀 Deploy website on push to dev
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      # setup composer
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - name: Build source files
        run: |
          yarn install
          yarn build
      - name: 📂 Sync files
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ secrets.WPE_ENV }}
          SRC_PATH: dist/pulse_theme
          FLAGS: -azvr --exclude-from=deploy-exclude.txt
          REMOTE_PATH: wp-content/themes/
